# Generated by Django 5.2.8 on 2026-04-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='state',
        ),
        migrations.AddField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10),
        ),
    ]
