# Generated by Django 5.2.8 on 2026-04-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_refund_state_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='tax_type',
            field=models.CharField(choices=[('15', 'IVA 15% (General)'), ('0', 'IVA 0%'), ('NO', 'No objeto de IVA')], default='15', max_length=2),
        ),
        migrations.AddField(
            model_name='link',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=4),
        ),
        migrations.AlterField(
            model_name='link',
            name='include_igv',
            field=models.BooleanField(default=True),
        ),
    ]
