# Generated by Django 5.2.7 on 2025-11-04 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='CustomUser',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('phone', models.CharField(max_length=10)),
        ('identification', models.BigIntegerField(unique=True)),
        ('state', models.BooleanField(default=True)),
        ('email_active', models.BooleanField(default=False)),
        (
          'user',
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL
          ),
        ),
      ],
    ),
  ]
