# Generated by Django 5.2.7 on 2025-11-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_customuser_user_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
