# Generated by Django 5.2.8 on 2026-03-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_bank_link_payment_paymentmethod_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='link',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='link',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
