# Generated by Django 5.2.8 on 2026-04-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_available_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin_role',
            field=models.BooleanField(default=False),
        ),
    ]
