# Generated by Django 5.2.8 on 2026-04-05 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_available_balance'),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='banking.paymentmethod')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='accounts.customuser')),
            ],
        ),
    ]
